config/routes.rb
BusinessTask::Application.routes.draw do
  resources :business_alerts

end

app/models/business_alert.rb
class BusinessAlert < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/business_alerts_controller.rb
class BusinessAlertsController < ApplicationController
  before_action :set_business_alert, only: [:show, :edit, :update, :destroy]

  # GET /business_alerts
  # GET /business_alerts.json
  def index
    @business_alerts = BusinessAlert.all
  end

  # GET /business_alerts/1
  # GET /business_alerts/1.json
  def show
  end

  # GET /business_alerts/new
  def new
    @business_alert = BusinessAlert.new
  end

  # GET /business_alerts/1/edit
  def edit
  end

  # POST /business_alerts
  # POST /business_alerts.json
  def create
    @business_alert = BusinessAlert.new(business_alert_params)

    respond_to do |format|
      if @business_alert.save
        format.html { redirect_to @business_alert, notice: 'Business alert was successfully created.' }
        format.json { render action: 'show', status: :created, location: @business_alert }
      else
        format.html { render action: 'new' }
        format.json { render json: @business_alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /business_alerts/1
  # PATCH/PUT /business_alerts/1.json
  def update
    respond_to do |format|
      if @business_alert.update(business_alert_params)
        format.html { redirect_to @business_alert, notice: 'Business alert was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @business_alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /business_alerts/1
  # DELETE /business_alerts/1.json
  def destroy
    @business_alert.destroy
    respond_to do |format|
      format.html { redirect_to business_alerts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business_alert
      @business_alert = BusinessAlert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_alert_params
      params.require(:business_alert).permit(:date, :title, :detail)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/business_alerts_helper.rb
module BusinessAlertsHelper
end

app/views/business_alerts/_form.html.erb
<%= form_for(@business_alert) do |f| %>
  <% if @business_alert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@business_alert.errors.count, "error") %> prohibited this business_alert from being saved:</h2>

      <ul>
      <% @business_alert.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :detail %><br>
    <%= f.text_area :detail %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/business_alerts/edit.html.erb
<h1>Editing business_alert</h1>

<%= render 'form' %>

<%= link_to 'Show', @business_alert %> |
<%= link_to 'Back', business_alerts_path %>

app/views/business_alerts/index.html.erb
<h1>Listing business_alerts</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Title</th>
      <th>Detail</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @business_alerts.each do |business_alert| %>
      <tr>
        <td><%= business_alert.date %></td>
        <td><%= business_alert.title %></td>
        <td><%= business_alert.detail %></td>
        <td><%= link_to 'Show', business_alert %></td>
        <td><%= link_to 'Edit', edit_business_alert_path(business_alert) %></td>
        <td><%= link_to 'Destroy', business_alert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Business alert', new_business_alert_path %>

app/views/business_alerts/new.html.erb
<h1>New business_alert</h1>

<%= render 'form' %>

<%= link_to 'Back', business_alerts_path %>

app/views/business_alerts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @business_alert.date %>
</p>

<p>
  <strong>Title:</strong>
  <%= @business_alert.title %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @business_alert.detail %>
</p>

<%= link_to 'Edit', edit_business_alert_path(@business_alert) %> |
<%= link_to 'Back', business_alerts_path %>

app/views/businesses/_form.html.erb
<%= form_for(@business) do |f| %>
  <% if @business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
      <% @business.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :alerts %><br>
    <%= f.text_field :alerts %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :detail %><br>
    <%= f.text_area :detail %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BusinessTask</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>